version: '3.8'
services:
  mongo-1:
    image: mongo:4.2
    container_name: mongo
    ports:
     - target: 27017
       published: 27016
       protocol: tcp
       mode: host
    networks:
     - notify-net-1
    volumes:
      - mongo_data:/data/db  # Persistent volume for MongoDB
      - mongo_config:/data/configdb  # Configuration volume

  notify-redis-1:
    image: redis:6.0.1
    container_name: notify-redis-1
    ports:
     - "6379:6379"
    networks:
     - notify-net-1
  notify-node-1:
    build: ./
    container_name: notify-node-1
    ports: 
     - "8080:8080"
    restart: on-failure
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
     - NODE_ENV=development
    env_file: ".env"
    depends_on:
     - mongo-1
     - notify-redis-1
    volumes:
     - .:/notify-1
     - /node_modules
    networks:
     - notify-net-1
volumes:
  mongo_data:
  mongo_config:

networks:
  notify-net-1:
    driver: bridge
